apiVersion: v1
kind: Namespace
metadata:
  name: micros-02-qa
  labels:
    app.kubernetes.io/name: micros-02-qa
    app.kubernetes.io/part-of: micros-02-two-services-over-http
    environment: qa
    purpose: kubernetes-qa-lab