apiVersion: v1
kind: Secret
metadata:
  name: catalog-database-secret
  namespace: micros-02-qa
  labels:
    app.kubernetes.io/name: catalog-database
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: micros-02-two-services-over-http
type: Opaque
stringData:
  postgres-database: catalog_service
  postgres-username: catalog_user
  postgres-password: replace-me
---
apiVersion: v1
kind: Secret
metadata:
  name: pricing-database-secret
  namespace: micros-02-qa
  labels:
    app.kubernetes.io/name: pricing-database
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: micros-02-two-services-over-http
type: Opaque
stringData:
  postgres-database: pricing_service
  postgres-username: pricing_user
  postgres-password: replace-me