apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "micros-02.catalogName" . }}-config
  labels:
    {{- include "micros-02.labels" . | nindent 4 }}
    app.kubernetes.io/name: catalog-service
    app.kubernetes.io/component: api

data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.catalog.config.environment | quote }}
  ASPNETCORE_HTTP_PORTS: {{ .Values.catalog.config.httpPorts | quote }}

  PricingService__BaseUrl: {{ printf "http://%s" (include "micros-02.pricingName" .) | quote }}

  PricingService__TimeoutSeconds: {{ .Values.catalog.config.pricingService.timeoutSeconds | quote }}
  PricingService__RetryCount: {{ .Values.catalog.config.pricingService.retryCount | quote }}
  PricingService__RetryDelayMilliseconds: {{ .Values.catalog.config.pricingService.retryDelayMilliseconds | quote }}