apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "micros-02.pricingName" . }}-config
  labels:
    {{- include "micros-02.labels" . | nindent 4 }}
    app.kubernetes.io/name: pricing-service
    app.kubernetes.io/component: api

data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.pricing.config.environment | quote }}
  ASPNETCORE_HTTP_PORTS: {{ .Values.pricing.config.httpPorts | quote }}