apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-service-config
  namespace: micros-02-qa
  labels:
    app.kubernetes.io/name: catalog-service
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: micros-02-two-services-over-http
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_HTTP_PORTS: "8080"

  PricingService__BaseUrl: "http://pricing-service"
  PricingService__TimeoutSeconds: "3"
  PricingService__RetryCount: "2"
  PricingService__RetryDelayMilliseconds: "200"